let data = [
    {
        id: "1",
        title: "Iron Man",
        phase: "Phase One",
        type: "movie",
        releaseDate: 39570,
        protaganist: "Iron Man",
        characters: ["Iron Man", "Pepper Potts"],
        status: "Released",
        rating: 7.9,
        runtime: "126 min",
        episodes: 1
    },
        {
          id: "2",
          title: "The Incredible Hulk",
          phase: "Phase One",
          type: "movie",
          releaseDate: 39612,
          protaganist: "Hulk",
          characters: ["Hulk"],
          status: "Released",
          rating: 6.7,
          runtime: "112 min",
          episodes: 1
        },
        {
          id: "3",
          title: "Iron Man 2",
          phase: "Phase One",
          type: "movie",
          releaseDate: 40305,
          protaganist: "Iron Man",
          characters: ["Iron Man", "War Machine", "Black Widow", "Pepper Potts"],
          status: "Released",
          rating: 7,
          runtime: "124 min",
          episodes: 1
        },
        {
          id: "4",
          title: "Thor",
          phase: "Phase One",
          type: "movie",
          releaseDate: 40669,
          protaganist: "Thor",
          characters: ["Thor", "Loki", "Jane Foster"],
          status: "Released",
          rating: 7,
          runtime: "115 min",
          episodes: 1
        },
        {
          id: "5",
          title: "Captain America: The First Avenger",
          phase: "Phase One",
          type: "movie",
          releaseDate: 40746,
          protaganist: "Captain America",
          characters: ["Captain America", "Peggy Carter"],
          status: "Released",
          rating: 6.9,
          runtime: "124 min",
          episodes: 1
        },
        {
          id: "6",
          title: "The Avengers",
          phase: "Phase One",
          type: "movie",
          releaseDate: 41033,
          protaganist: "The Avengers",
          characters: ["Iron Man", "Captain America", "Hulk", "Thor", "Black Widow", "Hawkeye", "Loki"],
          status: "Released",
          rating: 8.1,
          runtime: "143 min",
          episodes: 1
        },
        {
          id: "7",
          title: "Iron Man 3",
          phase: "Phase Two",
          type: "movie",
          releaseDate: 41397,
          protaganist: "Iron Man",
          characters: ["Iron Man", "Pepper Potts", "War Machine", "Iron Patriot"],
          status: "Released",
          rating: 7.2,
          runtime: "130 min",
          episodes: 1
        },
        {
          id: "8",
          title: "Thor: The Dark World",
          phase: "Phase Two",
          type: "movie",
          releaseDate: 41586,
          protaganist: "Thor",
          characters: ["Thor", "Jane Foster", "Loki"],
          status: "Released",
          rating: 6.9,
          runtime: "112 min",
          episodes: 1
        },
        {
          id: "9",
          title: "Captain America: The Winter Soldier",
          phase: "Phase Two",
          type: "movie",
          releaseDate: 41733,
          protaganist: "Captain America",
          characters: ["Captain America", "Winter Soldier", "Peggy Carter", "Falcon"],
          status: "Released",
          rating: 7.8,
          runtime: "136 min",
          episodes: 1
        },
        {
          id: "10",
          title: "Guardians of the Galaxy",
          phase: "Phase Two",
          type: "movie",
          releaseDate: 41852,
          protaganist: "Guardians of the Galaxy",
          characters: ["Star Lord", "Gamora", "Drax the Destroyer", "Groot", "Rocket", "Thanos"],
          status: "Released",
          rating: 8.1,
          runtime: "121 min",
          episodes: 1
        },
        {
          id: "11",
          title: "Avengers: Age of Ultron",
          phase: "Phase Two",
          type: "movie",
          releaseDate: 42125,
          protaganist: "The Avengers",
          characters: ["Iron Man", "Captain America", "Hulk", "Thor", "Black Widow", "Hawkeye", "Falcon"],
          status: "Released",
          rating: 7.3,
          runtime: "141 min",
          episodes: 1
        },
        {
          id: "12",
          title: "Ant-Man",
          phase: "Phase Two",
          type: "movie",
          releaseDate: 42202,
          protaganist: "Ant-Man",
          characters: ["Ant-Man", "Falcon"],
          status: "Released",
          rating: 7.3,
          runtime: "117 min",
          episodes: 1
        },
        {
          id: "13",
          title: "Captain America: Civil War",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 42496,
          protaganist: "Captain America",
          characters: ["Captain America", "Iron Man", "Black Widow", "Winter Soldier", "Falcon", "War Machine", "Hawkeye", "Black Panther", "Spider-Man", "Vison", "Scarlet Witch", "Ant-Man"],
          status: "Released",
          rating: 7.8,
          runtime: "147 min",
          episodes: 1
        },
        {
          id: "14",
          title: "Doctor Strange",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 42678,
          protaganist: "Doctor Strange",
          characters: ["Doctor Strange", "Wong"],
          status: "Released",
          rating: 7.5,
          runtime: "115 min",
          episodes: 1
        },
        {
          id: "15",
          title: "Guardians of the Galaxy Vol. 2",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 42860,
          protaganist: "Gaurdians of the Galaxy",
          characters: ["Star Lord", "Gamora", "Drax the Destroyer", "Groot", "Rocket", "Nebula"],
          status: "Released",
          rating: 7.7,
          runtime: "136 min",
          episodes: 1
        },
        {
          id: "16",
          title: "Spider-Man: Homecoming",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 42923,
          protaganist: "Spider-Man",
          characters: ["Spider-Man", "Iron Man"],
          status: "Released",
          rating: 7.5,
          runtime: "133 min",
          episodes: 1
        },
        {
          id: "17",
          title: "Thor: Ragnarok",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 43042,
          protaganist: "Thor",
          characters: ["Thor", "Loki", "Hulk", "Valkyrie"],
          status: "Released",
          rating: 7.9,
          runtime: "130 min",
          episodes: 1
        },
        {
          id: "18",
          title: "Black Panther",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 43147,
          protaganist: "Black Panther",
          characters: ["Black Panther"],
          status: "Released",
          rating: 7.3,
          runtime: "134 min",
          episodes: 1
        },
        {
          id: "19",
          title: "Avengers: Infinity War",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 43217,
          protaganist: "The Avengers",
          characters: ["Captain America", "Iron Man", "Black Widow", "Winter Soldier", "Falcon", "War Machine", "Hawkeye", "Black Panther", "Spider-Man", "Vison", "Scarlet Witch", "Star Lord", "Drax the Destroyer", "Groot", "Rocket", "Nebula", "Gamora", "Pepper Potts", "Wong", "Doctor Strange", "Thanos"],
          status: "Released",
          rating: 8.5,
          runtime: "149 min",
          episodes: 1
        },
        {
          id: "20",
          title: "Ant-Man and the Wasp",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 43287,
          protaganist: "Ant-Man",
          characters: ["Ant-Man", "Wasp"],
          status: "Released",
          rating: 7.1,
          runtime: "118 min",
          episodes: 1
        },
        {
          id: "21",
          title: "Captain Marvel",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 43532,
          protaganist: "Captain Marvel",
          characters: ["Captain Marvel", "Nick Fury"],
          status: "Released",
          rating: 7.1,
          runtime: "123 min",
          episodes: 1
        },
        {
          id: "22",
          title: "Avengers: Endgame",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 43581,
          protaganist: "The Avengers",
          characters: ["Captain America", "Iron Man", "Black Widow", "Winter Soldier", "Falcon", "War Machine", "Hawkeye", "Black Panther", "Spider-Man", "Vison", "Scarlet Witch", "Star Lord", "Drax the Destroyer", "Groot", "Rocket", "Nebula", "Gamora", "Pepper Potts", "Wong", "Doctor Strange", "Captain Marvel", "Thanos", "Valkyrie"],
          status: "Released",
          rating: 8.8,
          runtime: "181 min",
          episodes: 1
        },
        {
          id: "23",
          title: "Spider-Man: Far from Home",
          phase: "Phase Three",
          type: "movie",
          releaseDate: 43648,
          protaganist: "Spider-Man",
          characters: ["Spider-Man", "Mystrio", "Nick Fury", "MJ"],
          status: "Released",
          rating: 7.5,
          runtime: "129 min",
          episodes: 1
        },
        {
          id: "24",
          title: "Black Widow",
          phase: "Phase Four",
          type: "movie",
          releaseDate: 44386,
          protaganist: "Black Widow",
          characters: ["Black Widow"],
          status: "Released",
          rating: 6.9,
          runtime: "134 min",
          episodes: 1
        },
        {
          id: "25",
          title: "Shang-Chi and the Legend of the Ten Rings",
          phase: "Phase Four",
          type: "movie",
          releaseDate: 44442,
          protaganist: "Shang-Chi",
          characters: ["Shang-Chi, Wong"],
          status: "Released",
          rating: 7.5,
          runtime: "132 min",
          episodes: 1
        },
        {
          id: "26",
          title: "Eternals",
          phase: "Phase Four",
          type: "movie",
          releaseDate: 44505,
          protaganist: "The Eternals",
          characters: ["Sersi", "Ikaris", "Kingo", "Sprite", "Makkari", "Druig", "Gilgamesh"],
          status: "Released",
          rating: 5.6,
          runtime: "156 min",
          episodes: 1
        },
        {
          id: "27",
          title: "Spider-Man: No Way Home",
          phase: "Phase Four",
          type: "movie",
          releaseDate: 44547,
          protaganist: "Spider-Man",
          characters: ["Spider-Man", "MJ", "Doctor Strange", "Wong"],
          status: "Released",
          rating: 7.9,
          runtime: "148 min",
          episodes: 1
        },
        {
          id: "28",
          title: "Doctor Strange in the Multiverse of Madness",
          phase: "Phase Four",
          type: "movie",
          releaseDate: 44687,
          protaganist: "Doctor Strange",
          characters: ["Doctor Strange","America Chavez", "Scarlet Witch"],
          status: "Released",
          rating: 6.5,
          runtime: "126 min",
          episodes: 1
        },
        {
          id: "29",
          title: "Thor: Love and Thunder",
          phase: "Phase Four",
          type: "movie",
          releaseDate: 44750,
          protaganist: "Thor",
          characters: ["Thor", "Jane Foster", "Valkyrie"],
          status: "Released",
          rating: 6.4,
          runtime: "119 min",
          episodes: 1
        },
        {
          id: "30",
          title: "Black Panther: Wakanda Forever",
          phase: "Phase Four",
          type: "movie",
          releaseDate: 44876,
          protaganist: "Black Panther",
          characters: ["Black Panther"],
          status: "Released",
          rating: 7.2,
          runtime: "161 min",
          episodes: 1
        },
        {
          id: "31",
          title: "Ant-Man and the Wasp: Quantumania",
          phase: "Phase Five",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "Ant-Man",
          characters: ["Ant-Man", "Wasp"],
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "32",
          title: "Guardians of the Galaxy Vol. 3",
          phase: "Phase Five",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "Guardians of the Galaxy",
          characters: ["Star Lord", "Nebula", "Drax the Destroyer", "Groot", "Rocket"],
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "33",
          title: "The Marvels",
          phase: "Phase Five",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "34",
          title: "Captain America: New World Order",
          phase: "Phase Five",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "35",
          title: "Thunderbolts",
          phase: "Phase Five",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "36",
          title: "Blade",
          phase: "Phase Five",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "37",
          title: "Deadpool 3",
          phase: "Phase Six",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "Deadpool",
          characters: "TBA",
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "38",
          title: "Fantastic Four",
          phase: "Phase Six",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "Fantstic Four",
          characters: "TBA",
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "39",
          title: "Avengers: The Kang Dynasty",
          phase: "Phase Six",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "40",
          title: "Avengers: Secret Wars",
          phase: "Phase Six",
          type: "movie",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          episodes: 1
        },
        {
          id: "41",
          title: "Agents of S.H.I.E.L.D.",
          phase: "N/A",
          type: "tv series",
          releaseDate: 41541,
          protaganist: "Agents of S.H.E.I.L.D",
          characters: ["Phil Coulson", "Pachakutiq", "Phil Coulson", "Melinda May", "Grant Ward", "Hive, Quake", "Leo Fitz", "Jemma Simmons", "Lance Hunter", "Bobbi Morse", "Al MacKenzie", "Lincoln Campbell", "Holden Radcliffe, Yo-Yo Rodriguez"],
          status: "Released",
          runtime: "43 min",
          episodes: 136
        },
        {
          id: "42",
          title: "Agent Carter",
          phase: "N/A",
          type: "tv series",
          releaseDate: 42010,
          protaganist: "Peggy Carter",
          characters: ["Peggy Carter"],
          status: "Released",
          runtime: "43 min",
          episodes: 18
        },
        {
          id: "43",
          title: "Inhumans",
          phase: "N/A",
          type: "tv series",
          releaseDate: 43007,
          protaganist: "Black Bolt",
          characters: ["Black Bolt", "Medusa, Karnak"],
          status: "Released",
          runtime: "43 min",
          episodes: 8
        },
        {
          id: "44",
          title: "Daredevil",
          phase: "N/A",
          type: "tv series",
          releaseDate: 42104,
          protaganist: "Daredevil",
          characters: ["Daredevil"],
          status: "Released",
          runtime: "43 min",
          episodes: 39
        },
        {
          id: "45",
          title: "Jessica Jones",
          phase: "N/A",
          type: "tv series",
          releaseDate: 42328,
          protaganist: "Jessica Jones",
          characters: ["Jessica Jones, Luke Cage"],
          status: "Released",
          runtime: "43 min",
          episodes: 39
        },
        {
          id: "46",
          title: "Luke Cage",
          phase: "N/A",
          type: "tv series",
          releaseDate: 42551,
          protaganist: "Luke Cage",
          characters: ["Luke Cage"],
          status: "Released",
          runtime: "43 min",
          episodes: 26
        },
        {
          id: "47",
          title: "Iron Fist",
          phase: "N/A",
          type: "tv series",
          releaseDate: 42811,
          protaganist: "Iron Fist",
          characters: ["Iron Fist", "Colleen Wing"],
          status: "Released",
          runtime: "43 min",
          episodes: 26
        },
        {
          id: "48",
          title: "The Defenders",
          phase: "N/A",
          type: "tv series",
          releaseDate: 42965,
          protaganist: "The Defenders",
          characters: ["Daredevil", "Jessica Jones", "Luke Cage", "Iron Fist"],
          status: "Released",
          runtime: "43 min",
          episodes: 8
        },
        {
          id: "49",
          title: "The Punisher",
          phase: "N/A",
          type: "tv series",
          releaseDate: 43056,
          protaganist: "The Punisher",
          characters: ["Punisher", "Micro"],
          status: "Released",
          runtime: "43 min",
          episodes: 26
        },
        {
          id: "50",
          title: "Runaways",
          phase: "N/A",
          type: "tv series",
          releaseDate: 43060,
          protaganist: "Alex Wilder",
          characters: ["Alex Wilder"],
          status: "Released",
          runtime: "43 min",
          episodes: 33
        },
        {
          id: "51",
          title: "Cloak & Dagger",
          phase: "N/A",
          type: "tv series",
          releaseDate: 43288,
          protaganist: "Cloak & Dagger",
          characters: ["Dagger", "Cloak"],
          status: "Released",
          runtime: "43 min",
          episodes: 20
        },
        {
          id: "52",
          title: "Helstrom",
          phase: "N/A",
          type: "tv series",
          releaseDate: 44120,
          protaganist:"Daimon Helstrom",
          characters: ["Daimon Helstrom"],
          status: "Released",
          runtime: "43 min",
          episodes: 10
        },
        {
          id: "53",
          title: "WandaVision",
          phase: "Phase Four",
          type: "tv series",
          releaseDate: 44211,
          protaganist:"Scarlet Witch",
          characters: ["Scarlet Witch", "Vision", "Agatha Harkness"],
          status: "Released",
          runtime: "43 min",
          episodes: 9
        },
        {
          id: "54",
          title: "The Falcon and the Winter Soldier",
          phase: "Phase Four",
          type: "tv series",
          releaseDate: 44274,
          protaganist: "Winter Soldier, Falcon",
          characters: ["Winter Soldier", "Falcon"],
          status: "Released",
          runtime: "43 min",
          episodes: 6
        },
        {
          id: "55",
          title: "Loki",
          phase: "Phase Four",
          type: "tv series",
          releaseDate: 44356,
          protaganist: "Loki",
          characters: ["Loki"],
          status: "Released",
          runtime: "43 min",
          episodes: 6
        },
        {
          id: "56",
          title: "What If...?",
          phase: "Phase Four",
          type: "tv series",
          releaseDate: 44419,
          protaganist: "All",
          characters: ["Peggy Carter", "Captain America", "Star Lord", "Black Panther", "Hulk", "Loki", "Doctor Stange", "Vision", "Winter Soldier", "And-Man", "Wasp", "Wong", "Black Widow", "Hawkeye", "Black Widow", "Iron Man", "Jane Foster", "Thor", "Captain America"],
          status: "Released",
          runtime: "43 min",
          episodes: 9
        },
        {
          id: "57",
          title: "Hawkeye",
          phase: "Phase Four",
          type: "tv series",
          releaseDate: 44524,
          protaganist: "Hawkeye",
          characters: ["Hawkeye"],
          status: "Released",
          runtime: "43 min",
          episodes: 6
        },
        {
          id: "58",
          title: "Moon Knight",
          phase: "Phase Four",
          type: "tv series",
          releaseDate: 44650,
          protaganist: "Moon Knight",
          characters: "Moon Knight",
          status: "Released",
          runtime: "43 min",
          episodes: 6
        },
        {
          id: "59",
          title: "Ms. Marvel",
          phase: "Phase Four",
          type: "tv series",
          releaseDate: 44720,
          protaganist: "Ms. Marvel",
          characters: ["Ms. Marvel"],
          status: "Released",
          runtime: "43 min",
          episodes: 6
        },
        {
          id: "60",
          title: "She-Hulk: Attorney at Law",
          phase: "Phase Four",
          type: "tv series",
          releaseDate: 44791,
          protaganist: "She-Hulk",
          characters: ["She-Hulk", "Hulk", "Titania"],
          status: "Released",
          runtime: "43 min",
          episodes: 9
        },
        {
          id: "61",
          title: "Secret Invasion",
          phase: "Phase Five",
          type: "tv series",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          rating: "TBA",
          runtime: "TBA",
          episodes: "TBA"
        },
        {
          id: "62",
          title: "Echo",
          phase: "Phase Five",
          type: "tv series",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          rating: "TBA",
          runtime: "TBA",
          episodes: "TBA"
        },
        {
          id: "63",
          title: "Ironheart",
          phase: "Phase Five",
          type: "tv series",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          rating: "TBA",
          runtime: "TBA",
          episodes: "TBA"
        },
        {
          id: "64",
          title: "Agatha: Coven of Chaos",
          phase: "Phase Five",
          type: "tv series",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          rating: "TBA",
          runtime: "TBA",
          episodes: "TBA"
        },
        {
          id: "65",
          title: "Daredevil: Born Again",
          phase: "Phase Five",
          type: "tv series",
          releaseDate: "TBA",
          protaganist: "TBA",
          characters: "TBA",
          status: "Unreleased",
          rating: "TBA",
          runtime: "TBA",
          episodes: "TBA"
        }
    ]
  
module.exports = data;